version: '3.8'

services:
  db:
    image: postgres:15.5
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_spring_develop:/var/lib/postgresql/data

volumes:
  postgres_data_spring_develop:
