spring:
  application:
    name: spring-boot-develop
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: 'true'
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    username: develop
    url: jdbc:postgresql://localhost:5432/develop
    password: develop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8090

application:
  security:
    jwt:
      secret-key: 656624227a5e50472d584e313b583d7c56512e69745c4c626e4d64234c
      expiration: 86400000
      refresh-token:
        expiration: 604800000

rabbitmq:
  queue:
    name: develop-queue
  exchange:
    name: develop-exchange
  routing-key: routing_key_develop